[package]
name = "day_16"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
itertools = "0.10.3"
bitvec = "0.22.3"
hex = "0.4.3"
