[package]
name = "day_5"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
itertools = "0.10.1"
thiserror = "1.0.30"
anyhow = "1.0.51"
ndarray = "0.15.4"
